services:
  homepage:
    build: homepage
    ports:
      - 80:80
    depends_on:
      - dataapi
  dataapi:
    build: dataapi
    ports: 
      - 3000:3000
    depends_on:
      - homepageDatabase
  homepageDatabase:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todos
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - my-todos:/var/lib/mysql
      - ./database_init:/tmp/database
    command: --init-file="/tmp/database/database_init.sql"
volumes:
  my-todos: