services:
  homepage:
    build: homepage
    ports:
      - 80:80
    depends_on:
      - dataapi
  dataapi:
    build: dataapi
    ports: 
      - 3000:3000
    depends_on:
      - homepageDatabase
    command: bash -c 'sleep 3; node app.js' # database requires delay
  homepageDatabase:
    image: mysql:8
    environment:
      MYSQL_USER: dataapi
      MYSQL_PASSWORD: dataapi_password
      MYSQL_ROOT_PASSWORD: root_password # required by mysql
      MYSQL_DATABASE: homepage
      MYSQL_TCP_PORT: 3307 # 3306 may be used by another app
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - 3307:3307
    volumes:
      - homepage:/var/lib/mysql
      # leave database initalization to dataapi
      # - ./database_init:/tmp/database
    # command: --init-file="/tmp/database/database_init.sql"
volumes:
  homepage: